### ISSUE TITLE
just a suggestion about the new breathplay collar

### ISSUE THREAD

**Issue by meandred** [littlesera/LSCG#114] opened 2023-06-25 18:54 UTC
if set to the default collar type could the new breathplay collar be modified to work for crafted versions of that default collar type
or a setting be added for all collars to be affected by the breathplay triggers

**Comment by littlesera** [comment] 2023-06-25 19:08
Will consider adding a "collar-agnostic" setting. The original design was a 'module' that was attached to a specific collar.

Dupe of #111

**Closed by littlesera** 2023-06-25 19:08 UTC
